export {default as HomePg} from "./HomePg/HomePg";
export {default as OnlineGiving} from "./OnlineGiving";
export {default as Ministries} from "./Ministries";
export {default as ContactPg} from "./ContactPg/ContactPg";
export {default as DeptGroup} from "./DeptGroups";
export {default as DadMumEPG} from "./DadMumEPG";
export {default as ShareTestimony} from "./ShareTestimony"
export {default as MissionVision} from "./MissionVision";
export {default as Calendar} from "./Calendar";
export {default as History} from "./History"
export {default as AboutPg} from "./AboutPg";